In [1]:
import pandas as pd

In [2]:
pd.__version__

'0.20.3'

In [3]:
import numpy as np

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([ 0.25,  0.5 ,  0.75,  1.  ])

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [7]:

population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

In [8]:
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [9]:
population['California']

38332521

In [10]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

In [11]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [12]:
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [13]:
states.columns

Index(['area', 'population'], dtype='object')

In [14]:
states['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [15]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [16]:
pd.DataFrame(np.random.rand(3,2),
            columns=['foo','bar'],
            index=['a','b','c'])

foo       bar
a  0.482684  0.968850
b  0.610082  0.639751
c  0.390569  0.787291

In [17]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [18]:
ind[1]

3

In [19]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [20]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [21]:
data.area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [22]:
data.area is data['area']

True

In [23]:
1 is 1

True

In [24]:
1 is 2

False

In [25]:
data['density'] = data['pop'] / data['area']

In [26]:
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [27]:
data.T

California       Florida      Illinois      New York         Texas
area     4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05  6.956620e+05
pop      3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07  2.644819e+07
density  9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02  3.801874e+01

In [28]:
data.values[0]

array([  4.23967000e+05,   3.83325210e+07,   9.04139261e+01])

In [29]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [30]:
data.loc[:'Florida',:'pop']

area       pop
California  423967  38332521
Florida     170312  19552860

In [31]:
data.ix[:3,:'pop']

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [34]:
data.loc[data.density>100,['pop','density','area']]

pop     density    area
Florida   19552860  114.806121  170312
New York  19651127  139.076746  141297

In [35]:
data.iloc[0,2] = 90

In [36]:
data

area       pop     density
California  423967  38332521   90.000000
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [41]:
data['Florida':'New York']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763
New York  141297  19651127  139.076746

In [42]:
data[1:3]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [43]:
import pandas as pd

In [44]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])

In [45]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [46]:
data['b']

0.5

In [48]:
'a' in data

True

In [49]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [50]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [51]:
data['e']= 1.25

In [52]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [53]:
data['a':'e']

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [54]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [55]:
data[(data>0.3)&(data<0.8)]

b    0.50
c    0.75
dtype: float64

In [56]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [57]:
data[0:2]

a    0.25
b    0.50
dtype: float64

Index Preservation

In [58]:
import pandas as pd
import numpy as np

In [59]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [60]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),
                 columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [61]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [62]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [63]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [64]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [65]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [74]:

A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [75]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [76]:
B = pd.DataFrame(rng.randint(0,20,(3,3)),
                columns=list('BAC'))

In [77]:
B

B   A   C
0   3  13  17
1   8   1  19
2  14   6  11

In [78]:
A

0    2
1    4
2    6
dtype: int64

In [79]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  7  14
1  2  13

In [80]:

B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  0  3  1
1  7  3  1
2  5  5  9

In [81]:
A + B

A     B   C
0  10.0  14.0 NaN
1   5.0  20.0 NaN
2   NaN   NaN NaN

In [93]:
fill = A.stack().mean()

In [94]:
fill

9.0

In [95]:
A.add(B,fill_value=fill)

A     B     C
0  10.0  14.0  10.0
1   5.0  20.0  10.0
2  14.0  14.0  18.0

In [96]:
A = rng.randint(10,size=(3,4))

In [97]:
A

array([[3, 5, 1, 9],
       [1, 9, 3, 7],
       [6, 8, 7, 4]])

In [98]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-2,  4,  2, -2],
       [ 3,  3,  6, -5]])

In [99]:
df = pd.DataFrame(A,columns=list('QRST'))
df

Q  R  S  T
0  3  5  1  9
1  1  9  3  7
2  6  8  7  4

In [105]:
df.iloc[1,:]

Q    1
R    9
S    3
T    7
Name: 1, dtype: int64

In [106]:
df - df.iloc[1,:]

Q  R  S  T
0  2 -4 -2  2
1  0  0  0  0
2  5 -1  4 -3

In [107]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -2  0 -4  4
1 -8  0 -6 -2
2 -2  0 -1 -4

In [108]:
halfrow = df.iloc[0,::2]

In [109]:
halfrow

Q    3
S    1
Name: 0, dtype: int64

In [110]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -2.0 NaN  2.0 NaN
2  3.0 NaN  6.0 NaN

In [111]:
import pandas as pd
import numpy as np

In [112]:
vals = np.array([1,None,3,4])

In [113]:
vals

array([1, None, 3, 4], dtype=object)

In [114]:
for dtype in ['object','int']:
    print('dtype =',dtype)
    %timeit np.arange(1E6,dtype=dtype).sum()
    print()

dtype = object
67.6 ms ± 3.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
2.18 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [116]:
%timeit np.arange(10,dtype='object').sum()

3.2 µs ± 95.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [117]:
vals.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [118]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [119]:
1+np.nan

nan

In [120]:
0*np.nan

nan

In [121]:
pd.Series(range(2),dtype=int)

0    0
1    1
dtype: int64

In [122]:
data = pd.Series([1, np.nan, 'hello', None])

In [123]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [125]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [126]:
data.dropna()

0        1
2    hello
dtype: object

In [127]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [128]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [130]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [131]:
df[3] = np.nan

In [134]:
df.iloc[2,:] = np.nan

In [135]:
df

0    1    2   3
0  1.0  NaN  2.0 NaN
1  2.0  3.0  5.0 NaN
2  NaN  NaN  NaN NaN

In [136]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [137]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [138]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [139]:
df

0    1    2   3
0  1.0  NaN  2.0 NaN
1  2.0  3.0  5.0 NaN
2  NaN  NaN  NaN NaN

In [141]:
df.fillna(method='ffill',axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  NaN  NaN  NaN

In [142]:

index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [143]:
index = pd.MultiIndex.from_tuples(index)

In [145]:
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [146]:
pop  = pop.reindex(index)

In [147]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [148]:
pop[:,2000]

California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [150]:
pop['California',2000]

33871648

In [152]:
pop.unstack().stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [153]:
pop_df = pd.DataFrame({'total':pop,
                      'under18':[1,2,3,4,5,6]})
pop_df

total  under18
California 2000  33871648        1
           2010  37253956        2
New York   2000  18976457        3
           2010  19378102        4
Texas      2000  20851820        5
           2010  25145561        6

In [154]:
f_u18 = pop_df['under18'] / pop_df['total']

In [156]:
f_u18.unstack()

2000          2010
California  2.952322e-08  5.368557e-08
New York    1.580906e-07  2.064186e-07
Texas       2.397872e-07  2.386107e-07

In [158]:

df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.779056  0.293501
  2  0.231697  0.196497
b 1  0.959375  0.077276
  2  0.327916  0.578739

In [159]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
pd.MultiIndex.from