In [1]:
import pandas as pd

In [2]:
pd.__version__

'0.20.3'

In [3]:
import numpy as np

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([ 0.25,  0.5 ,  0.75,  1.  ])

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [7]:

population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

In [8]:
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [9]:
population['California']

38332521

In [10]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

In [11]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [12]:
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [13]:
states.columns

Index(['area', 'population'], dtype='object')

In [14]:
states['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [15]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [16]:
pd.DataFrame(np.random.rand(3,2),
            columns=['foo','bar'],
            index=['a','b','c'])

foo       bar
a  0.482684  0.968850
b  0.610082  0.639751
c  0.390569  0.787291

In [17]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [18]:
ind[1]

3

In [19]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [20]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [21]:
data.area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [22]:
data.area is data['area']

True

In [23]:
1 is 1

True

In [24]:
1 is 2

False

In [25]:
data['density'] = data['pop'] / data['area']

In [26]:
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [27]:
data.T

California       Florida      Illinois      New York         Texas
area     4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05  6.956620e+05
pop      3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07  2.644819e+07
density  9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02  3.801874e+01

In [28]:
data.values[0]

array([  4.23967000e+05,   3.83325210e+07,   9.04139261e+01])

In [29]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [30]:
data.loc[:'Florida',:'pop']

area       pop
California  423967  38332521
Florida     170312  19552860

In [31]:
data.ix[:3,:'pop']

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [34]:
data.loc[data.density>100,['pop','density','area']]

pop     density    area
Florida   19552860  114.806121  170312
New York  19651127  139.076746  141297

In [35]:
data.iloc[0,2] = 90

In [36]:
data

area       pop     density
California  423967  38332521   90.000000
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [41]:
data['Florida':'New York']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763
New York  141297  19651127  139.076746

In [42]:
data[1:3]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [43]:
import pandas as pd

In [44]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])

In [45]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [46]:
data['b']

0.5

In [48]:
'a' in data

True

In [49]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [50]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [51]:
data['e']= 1.25

In [52]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [53]:
data['a':'e']

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [54]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [55]:
data[(data>0.3)&(data<0.8)]

b    0.50
c    0.75
dtype: float64

In [56]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [57]:
data[0:2]

a    0.25
b    0.50
dtype: float64

Index Preservation

In [58]:
import pandas as pd
import numpy as np

In [59]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [60]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),
                 columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [61]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [62]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [63]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [64]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [65]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [74]:

A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [75]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [76]:
B = pd.DataFrame(rng.randint(0,20,(3,3)),
                columns=list('BAC'))

In [77]:
B

B   A   C
0   3  13  17
1   8   1  19
2  14   6  11

In [78]:
A

0    2
1    4
2    6
dtype: int64

In [79]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  7  14
1  2  13

In [80]:

B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  0  3  1
1  7  3  1
2  5  5  9

In [81]:
A + B

A     B   C
0  10.0  14.0 NaN
1   5.0  20.0 NaN
2   NaN   NaN NaN

In [93]:
fill = A.stack().mean()

In [94]:
fill

9.0

In [95]:
A.add(B,fill_value=fill)

A     B     C
0  10.0  14.0  10.0
1   5.0  20.0  10.0
2  14.0  14.0  18.0

In [96]:
A = rng.randint(10,size=(3,4))

In [97]:
A

array([[3, 5, 1, 9],
       [1, 9, 3, 7],
       [6, 8, 7, 4]])

In [98]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-2,  4,  2, -2],
       [ 3,  3,  6, -5]])

In [99]:
df = pd.DataFrame(A,columns=list('QRST'))
df

Q  R  S  T
0  3  5  1  9
1  1  9  3  7
2  6  8  7  4

In [105]:
df.iloc[1,:]

Q    1
R    9
S    3
T    7
Name: 1, dtype: int64

In [106]:
df - df.iloc[1,:]

Q  R  S  T
0  2 -4 -2  2
1  0  0  0  0
2  5 -1  4 -3

In [107]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -2  0 -4  4
1 -8  0 -6 -2
2 -2  0 -1 -4

In [108]:
halfrow = df.iloc[0,::2]

In [109]:
halfrow

Q    3
S    1
Name: 0, dtype: int64

In [110]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -2.0 NaN  2.0 NaN
2  3.0 NaN  6.0 NaN

In [111]:
import pandas as pd
import numpy as np

In [112]:
vals = np.array([1,None,3,4])

In [113]:
vals

array([1, None, 3, 4], dtype=object)

In [114]:
for dtype in ['object','int']:
    print('dtype =',dtype)
    %timeit np.arange(1E6,dtype=dtype).sum()
    print()

dtype = object
67.6 ms ± 3.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
2.18 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [116]:
%timeit np.arange(10,dtype='object').sum()

3.2 µs ± 95.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [117]:
vals.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [118]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [119]:
1+np.nan

nan

In [120]:
0*np.nan

nan

In [121]:
pd.Series(range(2),dtype=int)

0    0
1    1
dtype: int64

In [122]:
data = pd.Series([1, np.nan, 'hello', None])

In [123]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [125]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [126]:
data.dropna()

0        1
2    hello
dtype: object

In [127]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [128]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [130]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [131]:
df[3] = np.nan

In [134]:
df.iloc[2,:] = np.nan

In [135]:
df

0    1    2   3
0  1.0  NaN  2.0 NaN
1  2.0  3.0  5.0 NaN
2  NaN  NaN  NaN NaN

In [136]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [137]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [138]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [139]:
df

0    1    2   3
0  1.0  NaN  2.0 NaN
1  2.0  3.0  5.0 NaN
2  NaN  NaN  NaN NaN

In [141]:
df.fillna(method='ffill',axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  NaN  NaN  NaN

In [142]:

index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [143]:
index = pd.MultiIndex.from_tuples(index)

In [145]:
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [146]:
pop  = pop.reindex(index)

In [147]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [148]:
pop[:,2000]

California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [150]:
pop['California',2000]

33871648

In [152]:
pop.unstack().stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [153]:
pop_df = pd.DataFrame({'total':pop,
                      'under18':[1,2,3,4,5,6]})
pop_df

total  under18
California 2000  33871648        1
           2010  37253956        2
New York   2000  18976457        3
           2010  19378102        4
Texas      2000  20851820        5
           2010  25145561        6

In [154]:
f_u18 = pop_df['under18'] / pop_df['total']

In [156]:
f_u18.unstack()

2000          2010
California  2.952322e-08  5.368557e-08
New York    1.580906e-07  2.064186e-07
Texas       2.397872e-07  2.386107e-07

In [158]:

df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.779056  0.293501
  2  0.231697  0.196497
b 1  0.959375  0.077276
  2  0.327916  0.578739

In [159]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [162]:
def make_df(cols,ind):
    """
    Quickly make a dataframe"""
    data = {c:[str(c) + str(i) for i in ind]
           for c in cols}
    return pd.DataFrame(data)

make_df('ABC',range(1,4,1))

A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3

In [164]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

In [165]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
x = [[1,2],
    [3,4]]
np.concatenate([x,x],axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [168]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [173]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
display('df1', 'df2', 'pd.concat([df1, df2],axis=0)')

df1
    A   B
0  A1  B1
1  A2  B2

df2
    A   B
0  A3  B3
1  A4  B4

pd.concat([df1, df2],axis=0)
    A   B
0  A1  B1
1  A2  B2
0  A3  B3
1  A4  B4

In [170]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
display('df3', 'df4', "pd.concat([df3, df4], axis=1)")

df3
    A   B
0  A0  B0
1  A1  B1

df4
    C   D
0  C0  D0
1  C1  D1

pd.concat([df3, df4], axis=1)
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [174]:

x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index  # make duplicate indices!
display('x', 'y', 'pd.concat([x, y])')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y])
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [175]:
try:
    pd.concat([x,y],verify_integrity=True)
except ValueError as e:
    print(e)

Indexes have overlapping values: [0, 1]


In [176]:
display('x','y','pd.concat([x,y],ignore_index=True)')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x,y],ignore_index=True)
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [177]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display('df1', 'df2')

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [178]:
df3 = pd.merge(df1,df2)

In [179]:
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [180]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
display('df3', 'df4', 'pd.merge(df3, df4)')

df3
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

df4
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

pd.merge(df3, df4)
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [181]:

df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})
display('df1', 'df5', "pd.merge(df1, df5)")

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df5
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

pd.merge(df1, df5)
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [182]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
display('df1', 'df3', 'pd.merge(df1, df3, left_on="employee", right_on="name")')

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df3
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

pd.merge(df1, df3, left_on="employee", right_on="name")
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [183]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [185]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
display('df1a','df2a')

df1a
                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

In [186]:
display('df1a','df2a','pd.merge(df1a,df2a,left_index=True,right_index=True)')

df1a
                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

pd.merge(df1a,df2a,left_index=True,right_index=True)
                group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [187]:
# Following are shell commands to download the data
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57935  100 57935    0     0  19311      0  0:00:03  0:00:03 --:--:-- 16667
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   835  100   835    0     0    835      0  0:00:01 --:--:--  0:00:01  1136
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   872  100   872    0     0    872      0  0:00:01 --:--:--  0:00:01   959


In [188]:
!ls

Pandas.ipynb         state-abbrevs.csv    state-population.csv
README.md            state-areas.csv


In [189]:
!pwd

/Users/momo/Jupyter/data-science-ipython-notebooks


In [190]:
!git add *

In [191]:
!git status

On branch master
Your branch is up-to-date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   Pandas.ipynb
	new file:   state-abbrevs.csv
	new file:   state-areas.csv
	new file:   state-population.csv

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.ipynb_checkpoints/



In [192]:
!git commit -m "Download some csv file for pandas "

[master b87b7a6] Download some csv file for pandas
 4 files changed, 4772 insertions(+), 2 deletions(-)
 create mode 100644 state-abbrevs.csv
 create mode 100644 state-areas.csv
 create mode 100644 state-population.csv


In [193]:
!git status

On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.ipynb_checkpoints/

nothing added to commit but untracked files present (use "git add" to track)


In [194]:
! git push origin master

Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 22.14 KiB | 5.54 MiB/s, done.
Total 6 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:PeinWu/data-science-ipython-notebook.git
   46489e6..b87b7a6  master -> master


In [195]:
!ls 

Pandas.ipynb         state-abbrevs.csv    state-population.csv
README.md            state-areas.csv


In [196]:
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')


In [197]:
print(pop.head());print(areas.head());print(abbrevs.head())

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA


In [198]:
merged = pd.merge(pop,abbrevs,how='outer',left_on='state/region',right_on='abbreviation')
merged = merged.drop('abbreviation',axis=1)
merged.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [200]:
merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state           96
dtype: int64

In [205]:
merged[merged['state'].isnull()].tail()

state/region     ages  year   population state
2539          USA    total  2010  309326295.0   NaN
2540          USA  under18  2011   73902222.0   NaN
2541          USA    total  2011  311582564.0   NaN
2542          USA  under18  2012   73708179.0   NaN
2543          USA    total  2012  313873685.0   NaN

In [206]:
merged.loc[merged['state'].isnull(),'state/region'].value_counts()

PR     48
USA    48
Name: state/region, dtype: int64

In [208]:
merged.loc[merged['state/region']=='PR','state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA','state'] = 'United State'
merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state            0
dtype: int64

In [209]:
final = pd.merge(merged,areas,on='state',how='left')
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [210]:
final.isnull().sum()

state/region      0
ages              0
year              0
population       20
state             0
area (sq. mi)    48
dtype: int64

In [213]:
final['state'][final['area (sq. mi)'].isnull()].unique()

array(['United State'], dtype=object)

In [214]:
final.dropna(inplace=True)

In [215]:
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [226]:
final.query('year == 2010 & ages == "total"')

state/region   ages  year  population                 state  \
3              AL  total  2010   4785570.0               Alabama   
91             AK  total  2010    713868.0                Alaska   
101            AZ  total  2010   6408790.0               Arizona   
189            AR  total  2010   2922280.0              Arkansas   
197            CA  total  2010  37333601.0            California   
283            CO  total  2010   5048196.0              Colorado   
293            CT  total  2010   3579210.0           Connecticut   
379            DE  total  2010    899711.0              Delaware   
389            DC  total  2010    605125.0  District of Columbia   
475            FL  total  2010  18846054.0               Florida   
485            GA  total  2010   9713248.0               Georgia   
570            HI  total  2010   1363731.0                Hawaii   
581            ID  total  2010   1570718.0                 Idaho   
666            IL  total  2010  12839695.0              Illinois   
677            IN  total  2010   6489965.0               Indiana   
762            IA  total  2010   3050314.0                  Iowa   
773            KS  total  2010   2858910.0                Kansas   
858            KY  total  2010   4347698.0              Kentucky   
869            LA  total  2010   4545392.0             Louisiana   
954            ME  total  2010   1327366.0                 Maine   
965            MD  total  2010   5787193.0              Maryland   
1050           MA  total  2010   6563263.0         Massachusetts   
1061           MI  total  2010   9876149.0              Michigan   
1146           MN  total  2010   5310337.0             Minnesota   
1157           MS  total  2010   2970047.0           Mississippi   
1242           MO  total  2010   5996063.0              Missouri   
1253           MT  total  2010    990527.0               Montana   
1338           NE  total  2010   1829838.0              Nebraska   
1349           NV  total  2010   2703230.0                Nevada   
1434           NH  total  2010   1316614.0         New Hampshire   
1445           NJ  total  2010   8802707.0            New Jersey   
1530           NM  total  2010   2064982.0            New Mexico   
1541           NY  total  2010  19398228.0              New York   
1626           NC  total  2010   9559533.0        North Carolina   
1637           ND  total  2010    674344.0          North Dakota   
1722           OH  total  2010  11545435.0                  Ohio   
1733           OK  total  2010   3759263.0              Oklahoma   
1818           OR  total  2010   3837208.0                Oregon   
1829           PA  total  2010  12710472.0          Pennsylvania   
1914           RI  total  2010   1052669.0          Rhode Island   
1925           SC  total  2010   4636361.0        South Carolina   
2010           SD  total  2010    816211.0          South Dakota   
2021           TN  total  2010   6356683.0             Tennessee   
2106           TX  total  2010  25245178.0                 Texas   
2117           UT  total  2010   2774424.0                  Utah   
2202           VT  total  2010    625793.0               Vermont   
2213           VA  total  2010   8024417.0              Virginia   
2298           WA  total  2010   6742256.0            Washington   
2309           WV  total  2010   1854146.0         West Virginia   
2394           WI  total  2010   5689060.0             Wisconsin   
2405           WY  total  2010    564222.0               Wyoming   
2490           PR  total  2010   3721208.0           Puerto Rico   

      area (sq. mi)  
3           52423.0  
91         656425.0  
101        114006.0  
189         53182.0  
197        163707.0  
283        104100.0  
293          5544.0  
379          1954.0  
389            68.0  
475         65758.0  
485         59441.0  
570         10932.0  
581         83574.0  
666         57918.0  
677         36420.0  
762         56276.0  
773         82282.0  
858 

In [218]:
data2010.head

state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [222]:
final[(final['year'] == 2010) & (final['ages'] == 'total')].head()

state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [227]:
data2010 = final[(final['year'] == 2010) & (final['ages'] == 'total')]

In [228]:
data2010.head()

state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [229]:
data2010.set_index('state',inplace=True)
density = data2010['population'] / data2010['area (sq. mi)']

In [230]:
density.sort_values(ascending=False,inplace=True)
density.head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64

In [231]:
density.tail()

state
South Dakota    10.583512
North Dakota     9.537565
Montana          6.736171
Wyoming          5.768079
Alaska           1.087509
dtype: float64